// config.yml
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.4.0
      - image: circleci/mongo:3.4
    working_directory: ~/repo
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run db:seed
      - run: npm test